### PR TITLE
exception handler added to main function

### LINKED ISSUE #39: If a directory doesn't exist, nothing happens when remove command is used
Nothing happens if directory doesn't exist, example command:
`antler-proj remove /not/existing/dir dep test_dep1 test_app1`

We should throw an error in this scenario

### PR DESCRIPTION
**Pull request by dimas1185**
resolves #39

### CODE REVIEW

File: tools/main.cpp [hunk 1]
```diff
@@ -74,7 +74,11 @@ int main(int argc, char** argv) {
 
    try {
       return runner.exec();
-   } catch(...) {
+   } catch(std::exception& ex) {
```
Comment (mikelik) [inline tools/main.cpp:77]:
```suggestion
   } catch(const std::exception& ex) {

```

**Review by mikelik — APPROVED** [review]

**Review by mikelik — APPROVED** [review]

**Review by ScottBailey — APPROVED** [review]
LGTM, Thanks!
