### PR TITLE
Fix description of `antler-proj remove`

### LINKED ISSUE #14: Fix description of `antler-proj remove`
Correct descriptions of the commands.

Example:

`./antler-proj remove --help`

returns wrong description:

Add an app, dependency, library or test to your project.

### PR DESCRIPTION
**Pull request by mikelik**
Resolves #14

### CODE REVIEW

**Review by jolly-fellow — APPROVED** [review]

File: tools/update.hpp [hunk 1]
```diff
@@ -109,7 +109,7 @@ namespace antler {
 
       update_project(CLI::App& app) {
          path = system::fs::current_path().string();
-         subcommand = app.add_subcommand("update", "Update an app, dependency, library or test to your project.");
+         subcommand = app.add_subcommand("update", "Update an app, dependency, library or test of your project.");
```
Comment (ScottBailey) [inline tools/update.hpp:112]:
```suggestion
         subcommand = app.add_subcommand("update", "Update an app, dependency, library or test in your project.");

```

**Review by ScottBailey — CHANGES_REQUESTED** [review]
See suggestion.

**Review by ScottBailey — APPROVED** [review]
