### PR TITLE
yml -> yaml rename

### LINKED ISSUE #24: Incorrect work of "init" command
1. New code in #22 creates a project file with extension "yml" but other parts of the code still work with extension "yaml" too. It leads to the following bug: When we have two project files with different extensions in the same directory antler-proj works with the file with "yaml" extension and ignore "yml" file. User may have the following problems because of this. Example:

We successfully created a project file. 
root@c1742fb0fdb3:/app# antler-proj init /host/home/alex/dev/projects/AntelopeIO/Clion_DUNE/test test_proj 0.1
[info_log] :: project.version 0.1
[info_log] :: Wrote project manifest to /host/home/alex/dev/projects/AntelopeIO/Clion_DUNE/test.

It calls project.yml.
But we already have a project.yaml file in the same directory.
Then we trying to add a new app to our new project:

root@c1742fb0fdb3:/app# antler-proj add /host/home/alex/dev/projects/AntelopeIO/Clion_DUNE/test app test_app c++       
[error_log] :: Object test_app already exists in project.
[error_log] :: failed to add app

and getting error because this app is exists in project.yaml file. 
It is impossible to understand what is the problem until the user don't check the "test" directory and content of project.yaml file.

I recommend to use only one extension everywhere in the code to avoid such kind of problems.

2. antler-proj overwrites an existing project file without warnings or prompt to choose what to do. It may lead to unexpected loosing of information.

root@c1742fb0fdb3:/app# antler-proj init /host/home/alex/dev/projects/AntelopeIO/Clion_DUNE/test test_proj
[info_log] :: project.version 0.0.0
[info_log] :: Wrote project manifest to /host/home/alex/dev/projects/AntelopeIO/Clion_DUNE/test.
PROJ "/host/home/alex/dev/projects/AntelopeIO/Clion_DUNE/test"
[info_log] :: Created project test_proj at location /host/home/alex/dev/projects/AntelopeIO/Clion_DUNE/test

root@c1742fb0fdb3:/app# antler-proj init /host/home/alex/dev/projects/AntelopeIO/Clion_DUNE/test test_proj
[info_log] :: project.version 0.0.0
[info_log] :: Wrote project manifest to /host/home/alex/dev/projects/AntelopeIO/Clion_DUNE/test.
PROJ "/host/home/alex/dev/projects/AntelopeIO/Clion_DUNE/test"
[info_log] :: Created project test_proj at location /host/home/alex/dev/projects/AntelopeIO/Clion_DUNE/test

### PR DESCRIPTION
**Pull request by dimas1185**
fixes #24

### CODE REVIEW

File: src/project.cpp [hunk 1]
```diff
@@ -87,10 +87,11 @@ bool project::update_path(system::fs::path& path) noexcept {
...
 
    for (;;) {
-      if (system::fs::exists(search_path / "project.yaml")) {
-         path = search_path / "project.yaml";
+      if (system::fs::exists(search_path / manifest_name)) {
+         path = search_path / manifest_name;
          return true;
       }
+      // alternative manifest name
       if (system::fs::exists(search_path / "project.yml")) {
```
Comment (ScottBailey) [inline src/project.cpp:95]: I like `project::manifest_name`. Should we add `project::manifest_alternate` or similar?

**Review by ScottBailey — APPROVED** [review]
Looks good, thanks!

I see there are conflicts between this branch and main. Please rerun regression tests after merging.

**Review by ankit-gautam23 — APPROVED** [review]
LGTM

**Review by ScottBailey — APPROVED** [review]

**Review by mikelik — APPROVED** [review]
